export enum TenantSubscriptionStatus {
  TRIAL = "TRIAL",
  ACTIVE = "ACTIVE",
  PAST_DUE = "PAST_DUE",
  CANCELLED = "CANCELLED",
}

export enum UserRole {
  ADMIN = "ADMIN",
  ACCOUNTANT = "ACCOUNTANT",
  LOGISTIC_WORKER = "LOGISTIC_WORKER",
  SECURITY = "SECURITY",
}

export enum SalesOrderStatus {
  INFORMATION_NEEDED = "INFORMATION_NEEDED",
  ASSIGN_VEHICLE = "ASSIGN_VEHICLE",
  VEHICLE_ASSIGNED = "VEHICLE_ASSIGNED",
  ARRIVED = "ARRIVED",
  GATE_IN = "GATE_IN",
  LOADING_START = "LOADING_START",
  LOADING_COMPLETE = "LOADING_COMPLETE",
  HOLD = "HOLD",
  DELETED = "DELETED",
  TRIP_INVOICED = "TRIP_INVOICED",
  GATE_OUT = "GATE_OUT",
  IN_JOURNEY = "IN_JOURNEY",
  COMPLETED = "COMPLETED",
  INVOICED = "INVOICED",
  CANCELLED = "CANCELLED",
}

export enum VehicleStatus {
  ASSIGNED = "ASSIGNED",
  ARRIVED = "ARRIVED",
  GATE_IN = "GATE_IN",
  LOADING_START = "LOADING_START",
  LOADING_COMPLETE = "LOADING_COMPLETE",
  TRIP_INVOICED = "TRIP_INVOICED",
  GATE_OUT = "GATE_OUT",
  IN_JOURNEY = "IN_JOURNEY",
  COMPLETED = "COMPLETED",
  INVOICED = "INVOICED",
  CANCELLED = "CANCELLED",
}

export enum VehicleInvoiceStatus {
  NONE = "NONE",
  INVOICE_CREATED = "INVOICE_CREATED",
  INVOICE_PAID = "INVOICE_PAID",
}

export enum TruckType {
  OPEN = "OPEN",
  CLOSED = "CLOSED",
  CLOSED_OPEN = "CLOSED_OPEN",
}

export enum TruckSize {
  NINE_MT = "NINE_MT",
  TWELVE_MT = "TWELVE_MT",
  SIXTEEN_MT = "SIXTEEN_MT",
  EIGHTEEN_MT = "EIGHTEEN_MT",
}

export enum LoadType {
  SINGLE = "SINGLE",
  CLUB = "CLUB",
}

export enum PaymentRequestType {
  ADVANCE_SHIPPING = "ADVANCE_SHIPPING",
  BALANCE_SHIPPING = "BALANCE_SHIPPING",
  FULL_SHIPPING_CHARGES = "FULL_SHIPPING_CHARGES",
  POINT_1_TO_POINT_2_TRANSFER = "POINT_1_TO_POINT_2_TRANSFER",
  UNLOADING_CHARGE = "UNLOADING_CHARGE",
  UNLOADING_DETENTION = "UNLOADING_DETENTION",
  MISCELLANEOUS_CHARGES = "MISCELLANEOUS_CHARGES",
}

export enum PaymentRequestStatus {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
}

export enum DocumentType {
  POD = "POD",
  LR_COPY = "LR_COPY",
  INVOICE_PDF = "INVOICE_PDF",
  VEHICLE_PHOTO = "VEHICLE_PHOTO",
  PAYMENT_PROOF = "PAYMENT_PROOF",
  BENEFICIARY_DOC = "BENEFICIARY_DOC",
}

export enum InvoiceStatus {
  DRAFT = "DRAFT",
  SENT = "SENT",
  PAID = "PAID",
}

export enum GateStatus {
  CHECK_IN = "CHECK_IN",
  GATE_IN = "GATE_IN",
  GATE_OUT = "GATE_OUT",
  CANCELLED = "CANCELLED",
}
